-- Auto-generated by scratchpad/gen-seed.js — carrier appointment seed data.
-- Idempotent: re-running updates the four appetite blocks + product/state/best_for
-- but PRESERVES any login info, status, and notes you've already entered.

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Annex Risk$c$, $c$annex-risk$c$, $c$not_started$c$, ARRAY[$c$Home$c$,$c$High Value Home$c$,$c$Dwelling Fire$c$,$c$Condo$c$]::text[], ARRAY[$c$FL$c$,$c$GA$c$,$c$MA$c$,$c$MD$c$,$c$NC$c$,$c$NJ$c$,$c$SC$c$,$c$TX$c$,$c$VA$c$]::text[], $c$E&S / non-admitted homeowners & high-value homes — primary, secondary, and annual/short-term rentals in coastal, hard-to-place states.$c$, $c$Excess & Surplus Lines homeowners' product.
Homeowners availability: FL GA MA MD NC NJ SC TX VA
- Primary, secondary, annual rentals
- Rental eligibility: 52-week annual rental and rented <20 weeks per year
High Value Homeowners availability: FL GA NC NJ SC TX VA
- Primary, secondary, short-term rentals
- Rental must not be greater than 20 weeks$c$, $c$Homeowners:
- Maximum TIV: $3.6M
- Coverage A: $100K-$2.0M
High Value:
- Maximum TIV: $5.0M
- Coverage A Primary Home: $2M-$3.12M
- Coverage A Secondary: $2M-$3.7M$c$, $c$- Last replaced year of heating / wiring / plumbing > 35 years old [High Value]
- Space heater, oil, or wood stove as primary heating source
- Galvanized, steel, iron, lead, clay, or polybutylene plumbing
- Electrical systems with fuses or service connection < 100 amps
- EIFS construction
- Less than 1,000 sq ft (DP3, HO3, HO5), or 500 sq ft (HO6)
- Unconventional, non-standard, or architecturally unique homes (mobile, modular, manufactured, log, airplane hangars, over-water)
- Farms or ranches (hobby or commercial) and/or properties over 10 acres
- Vacant, condemned, historic registry, or course-of-construction homes
- Properties constructed before 1950
- Homes held in trusts
- ISO Protection Class 9 & 10
- Electric breaker panels by Challenger, Federal Pacific, Zinsco & Pushmatic (any year)
- Square D Panels from 1988, 2004, 2006 & 2022
- Adobe or wood-shingle construction
- Roof of poor condition, wood shingles, or single membrane
- Lead paint or asbestos siding
- Homes in foreclosure
- Homes with more than 4 families
- Homes with two or more mortgages
- Coverage lapse over 180 days
- Daycare / assisted living / businesses with foot traffic / riding school / boarding school at premises
- Claims within the last 3 years: 2+ non-cat claims over $15k; one non-cat claim > $25k; open claims or theft claim over $10k; prior animal bite claims$c$, $c$- E&S: Agent must provide admitted carrier declinations as applicable in the state
- Roof: Coverage & acceptability based on roof age, material, and state/county (south FL)
- Exclusions/Limitations: dangerous dog breeds; swing sets; trampolines; pool claims if not fenced/to code; theft if prior theft claims; water damage limited if prior water losses
- Solar Panels: eligible, but not covered for wind & hail
- Lanais: screens/supports around pools/patios not covered; porch screens are covered
- Home Inspections: all homes inspected. Cov A < $750K & YOC after 1994 = exterior only; Cov A > $750K & YOC before 1994 = interior + exterior. Insured contacted within 5 business days; completed within 30 days or policy flat-cancelled
- High Value: all new business inspected interior + exterior (roof, siding, HVAC, plumbing, electrical)
- Payment: EFT, Credit Card, Mortgage Bill/Escrow
- Application must be e-signed within 7 days or policy flat-cancelled
- Coverage options: Extended Replacement Cost, Mold, Ordinance or Law, Water Damage, Personal Injury, Water Backup
- Geographic limits [High Value]: barrier islands, isolated coastal zips, FL Keys, Outer Banks, South Miami, Atlantic City, Monroe County FL$c$, 10)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Bamboo$c$, $c$bamboo$c$, $c$not_started$c$, ARRAY[$c$Home$c$,$c$Condo$c$,$c$Renters$c$,$c$Dwelling Fire$c$]::text[], ARRAY[$c$CA$c$,$c$TX$c$]::text[], $c$CA (admitted & E&S) and TX home, condo, renters and dwelling fire — townhomes/rowhouses and 1–4 unit dwellings.$c$, $c$CA Home [Admitted HO3 & E&S/Non-admitted HO3 & HO5]
- Homeowners; Secondary Home; includes Townhomes/Rowhouses
CA Dwelling Fire
- DP-1 or DP-3; includes Townhomes/Rowhouses; Single, Duplex, Triplex, Fourplex; Vacant acceptable on DP-1 up to 3 months
TX Products
- Homeowners [HO3 & HO5]; Secondary Home; Townhomes/Rowhouses [building 8 units or less]
- Condominium [HO6]
- Renters [HO4]
- Dwelling Fire/Landlord [DP-3]; includes Townhomes/Rowhouses; Single, Duplex, Triplex, Fourplex$c$, $c$CA Home [Admitted] / Dwelling Fire: $70K - $2M
CA Home [E&S/Non-admitted]: $1.5M Coverage A Max (HO3); $2.5M Coverage A Max (HO5)
TX Products:
- HO3/HO5: $25K - $1M
- DP3: $25K - $1M
- HO6 Coverage A: $5K - $500K; Coverage C: $15K - $250K
- HO4 Coverage C: $10K - $200K$c$, $c$CA:
- YOC prior to 1900
- Prior loss history: no more than 4 losses in past 60 months [E&S]; one theft or up to 2 property/liability (non-theft) [Admitted]; no more than one prior loss in past 60 months [Dwelling Fire]
TX:
- YOC prior to 1900
- 2+ non-natural chargeable losses within 3 years; open claims or claims in unknown status
- Poor condition, debris, unrepaired damage, extensive remodeling
- Any owed premiums on previously issued Bamboo policies
- Vacant properties
- Business on premises involving foot traffic; Daycare; Airbnb / short-term rental
- Unfenced swimming pool (unless fenced community where covenants disallow); pool must be maintained
- Siding: aluminum or asbestos
- Electric: knob and tube, fuse box or fuses
- Plumbing: polybutylene pipes
- Heating: must be thermostatically controlled; no secondary source as primary heat
- Protective devices: no working smoke detectors, fire extinguisher, dead bolts$c$, $c$CA Home / Dwelling Fire:
- Required documents must be signed by named insured on or before policy effective date
- Many optional coverages available; discounts for each product
- Do not require updates for plumbing, electrical or heating
- Trusts acceptable with trustee/beneficiary as additional insured
- LLCs acceptable with managing member as additional insured
TX:
- Coverage A must be 100% replacement cost; cannot be written > 35% of RCE
- Animal liability excluded on all forms; limited animal liability buyback available
- LLCs / Trusts acceptable (managing member / trustee as additional insured)
- Many optional coverages; discounts available
- Roofs subject to limited coverage depending on condition and age$c$, 20)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Branch$c$, $c$branch$c$, $c$not_started$c$, ARRAY[$c$Home$c$,$c$Auto (Standard)$c$,$c$Umbrella/Excess$c$,$c$Renters$c$]::text[], ARRAY[$c$AZ$c$,$c$OR$c$,$c$MT$c$,$c$NE$c$,$c$NM$c$,$c$UT$c$,$c$WI$c$,$c$MO$c$,$c$IL$c$,$c$IN$c$,$c$IA$c$,$c$KY$c$,$c$OH$c$,$c$AR$c$]::text[], $c$Bundled or monoline home & auto in select states; umbrella and renters available as endorsements.$c$, $c$Home:
- Bundle or monoline home; homes under 100 years old in AZ, OR, MT, NE, NM, UT, WI, MO, IL, IN, IA, KY, OH, AR
- Umbrella available as an endorsement on the home
- Can schedule jewelry (appraisal required in most cases)
- No excluded dog list — dog can't have bite history; will accept pools with a fence
- Inventory Discount available (app-based self inspection)
Auto:
- Bundle or monoline auto; telematics (Community Drive Discount) in most states
- System auto-tells you if ineligible with just name and address
All Other Lines:
- Umbrella endorsement on home; renters available as endorsement on auto in most states$c$, $c$Home:
- $1.2M Maximum Coverage A
- 100% Insurance to Value (system calculates replacement cost automatically)
- Must be in good condition
Auto:
- No lapse in coverage
- Six-month policy$c$, $c$Home:
- Not owner occupied; Age of home > 100 yrs
- Protection Class 9 & 10
- Vacant or under construction
- Short-term rental (Airbnb, VRBO, etc.)
- Historic or manufactured homes
Auto:
- No prior coverage; less than 6 months continuous coverage
- Ride share (Uber, Lyft, etc.)
- More than 2 cars per driver$c$, $c$Home (vary by state):
- Extended replacement cost available
- Roof replacement not available after 15 years
- Payment: Monthly or Pay in Full, EFT, Escrow Bill
Auto:
- Advanced Quote Discount (varies by state; AZ & WI live)
- Roadside assistance; 6-month term
- Payment: Monthly or Pay in Full, EFT (no mail-in payments)
- Monoline auto: preferred risks, multi-driver, higher liability limits$c$, 30)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Bristol West$c$, $c$bristol-west$c$, $c$not_started$c$, ARRAY[$c$Auto (Non-Standard)$c$]::text[], ARRAY[]::text[], $c$Non-standard auto (a Farmers Insurance company). Add your appointment/login details and paste the carrier one-sheet using the bulletin tool.$c$, null, null, null, $c$No carrier one-sheet was provided yet. Use the "Update from a bulletin" tool in the admin portal to paste Bristol West's appetite guide and Claude will fill these fields in.$c$, 40)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Chubb$c$, $c$chubb$c$, $c$not_started$c$, ARRAY[$c$Home$c$,$c$Auto (Standard)$c$,$c$Umbrella/Excess$c$,$c$Watercraft$c$,$c$Valuables$c$]::text[], ARRAY[]::text[], $c$High-net-worth package — home must include 2 of: auto, $50K jewelry, or $3M+ excess. Mega-yachts in FL.$c$, $c$Home:
- Home must also include at least 2 of these 3 additional lines: Auto, $50K jewelry, Excess of at least $3M
Auto: No monoline auto
Excess: No monoline excess; limits $1M-$50M; EPLI and Un/Underinsured limits by endorsement
Watercraft (Rec/Marine): Monoline or package (need not be tied to a HNW client)
- FL Only Mega-Yachts: $3M+ value, 70'+ length, full-time captain$c$, $c$Home:
- Minimum Coverage A: $1,000,000; minimum $2,500 deductible
- Minimum Condo/Renters combined A&A and Contents: $150,000; minimum $1,000 deductible
- $2M+ Primary Homes require Central Station Fire & Burglar Alarm incl. heat sensors in all enclosed areas (attic/garage/crawlspace)
- PC 1-8; all coastal & CAT exposures subject to UW pre-approval
Auto: Minimum 100/300/100 limits; minimum $500 deductibles Comp/Coll
Valuables: Jewelry $100K+ requires current appraisal or bill of sale; Fine Arts $250K+ requires appraisals or bill of sale
Excess Liability: Chubb auto not required, but Chubb underwrites the auto for acceptability$c$, $c$All Lines:
- Prior losses in last 3 years (one CAT-related loss subject to pre-approval)
- Prior lapse of coverage
Home:
- Under course of construction/renovation
- Not within 1000 ft of hydrant AND 5 miles of fire dept
- Secondary home without primary home
- EIFS unless built 2000+ and water managed
- Short-term rental
Auto: High Performance / Super Car (unless pre-approved)
Excess: High-profile client (unless pre-approved)$c$, $c$- No more than 3 rental units allowed
- Payment: EFT, monthly, quarterly, annual
- Client mobile app &/or online portal available
- Client phone # required at issuance to set up home inspection
- 100% insured to value required for Homeowners (verified via Chubb inspection)
- Lien-free credit available in many states
- Valuables credit on Home available in many states if jewelry is $25K+$c$, 50)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Clearcover$c$, $c$clearcover$c$, $c$not_started$c$, ARRAY[$c$Auto (Standard)$c$]::text[], ARRAY[]::text[], $c$Digital-first preferred auto; app-based; drivers without prior insurance acceptable.$c$, $c$Auto:
- Preferred drivers get most competitive rates
- Drivers without prior insurance are acceptable$c$, $c$- Drivers must have a valid/active US license (TX, IL can accept foreign license)
- Vehicles must have cost-new value < $100,000
- Vehicles must be 1982 or newer
- Vehicles must be registered to the named insured or spouse
- Payment: Monthly or PIF only; recurring credit card or EFT
- Valid email required (e-signature, paperless billing & policy output)$c$, $c$- Client does not have a valid email
- No capability to download the mobile app
- Commercial use$c$, $c$- Endorsements: Rideshare (passenger only — Uber/Lyft, no food delivery); Alternate Transportation for Loss of Use; Roadside Assistance on mobile app
- 6-month policy term only
- Best for digital-savvy clients who will download the app; claims filing < 4 minutes
- Target: above-avg insurance score, prior limits 100/300+, homeowners/renters, long-term prior carrier, no lapse, clean record, early shopper, pay in full$c$, 60)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Covercube$c$, $c$covercube$c$, $c$not_started$c$, ARRAY[$c$Auto (Non-Standard)$c$]::text[], ARRAY[$c$AZ$c$,$c$TX$c$]::text[], $c$AZ/TX monoline auto with app-based telematics; foreign/suspended licenses, salvage vehicles, SR-22; no credit check.$c$, $c$Auto (monoline):
- Liability only; Physical Damage OK up to 30 years old; Physical Damage OK with salvage vehicle (photos required); max 8 vehicles per policy
Drivers:
- Foreign drivers accepted (Mexico: Matricula, Passport, Voter ID, Birth Certificate, DL; Non-USA: international/foreign licenses)
- Suspended or expired licenses accepted (no SR-22 required); unverified/unlicensed accepted; registered/titled owners may be excluded; SR-22s accepted$c$, $c$- Each driver must download, activate & pair the free Covercube app to the vehicle's Bluetooth
- State minimum liability limits only
- Comprehensive & Collision must be written together
- All operators and household members age 15+ must be listed or excluded (eligible drivers may NOT be excluded)
- Physical Damage photos: two unobstructed photos showing all four sides + one clear odometer photo$c$, $c$- Former policyholder with unpaid balance to Covercube (must pay at submission)
- Any driver who cannot download/use the Covercube app
- More than 8 drivers on the policy
- Operators not residents of AZ or TX; any operator under age 15; any named insured under 18
- Operators with >2 at-fault accidents, OR 1 alcohol/drug charge, OR >1 major violation in last 36 months
- Combined violations over limit (max 2 at-fault OR 2 major OR 3 intermediate)
- Students residing/attending school outside AZ or TX
- Non-owned vehicles
- Vehicle value over $80,000 (liability) or $50,000 (physical damage)
- Commercial-type vehicles$c$, $c$- App uses a proprietary algorithm to measure driver focus & predict accident probability; drivers scored at each renewal (discounts or increases)
- No credit check
- Low down payments, flexible installments, recurring EFT
- Discounts: advance purchase (7+ days), paid-in-full (new business), auto-pay (EFT/recurring card), homeowners (proof required)
- Ridesharing Coverage Endorsement surcharge: 25% per vehicle used for ridesharing$c$, 70)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Cypress Property & Casualty$c$, $c$cypress-property-casualty$c$, $c$not_started$c$, ARRAY[$c$Condo$c$,$c$Home$c$]::text[], ARRAY[$c$FL$c$,$c$TX$c$]::text[], $c$Monoline condo & home in FL and TX including coastal (TX Tier 1/2/3); 40 years & newer; owner-occupied LLCs.$c$, $c$Condo (monoline — FL, TX): Owner Occupied, Tenant Occupied
Home (monoline — FL, TX): Owner Occupied; Primary, Secondary, Seasonal; Rental (FL only)$c$, $c$Condo:
- $35K Coverage A Min; $10K Coverage C Min; $500K Coverage A Max; $300K Coverage C Max
- 40 years & newer construction; can write coastal; Airbnb/VRBO 5 days or longer; owner-occupied LLCs
Home:
- $150K Coverage A Min - $2M Coverage A Max
- 40 years & newer; can write TX coastal (Tier 1, Tier 2, designated Tier 3); owner-occupied LLCs$c$, $c$Condo & Home:
- Vacant, under construction/renovation, foreclosure, for sale, or unoccupied
- Home-based business on property
- No more than 5 properties per named insured
- Roof age/type limits: 10 yrs 3-tab, 15 yrs architectural, 20 yrs tile, 30 yrs metal; solar panels or shingles
Home (additional):
- Working farms; open foundation, pier & beam, stilts or pilings
- Mobile, modular, pre-fab, trailer, log, earth homes
- Burglar bars, window A/C units$c$, $c$- Claim history based on the customer, not property; CLUE pulled after bind
- Scheduled personal property available; companion policy & PIF discounts; water leak detection discount; quotes expire after 59 days
- Animal liability exclusion with buyback (ineligible dog list, no bite history)
Condo:
- No Prior accepted with signed Statement of No Loss; no security requirements for seasonal/secondary/rentals; can write on any floor; Evergreen Edge bundle endorsement
Home:
- All HO3 include Exclusive Deductible Installment Plan (preferred vendors, pay deductible in 3 installments)
- No Prior accepted if under 30 days with signed Statement of No Loss
- Liability excluded if unfenced pool, trampolines, diving boards/slides
- Evergreen Edge / Evergreen Edge+ bundle endorsements; Coverage A must be 100% of RCE$c$, 80)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Dairyland$c$, $c$dairyland$c$, $c$not_started$c$, ARRAY[$c$Auto (Non-Standard)$c$,$c$Motorcycle$c$]::text[], ARRAY[]::text[], $c$Non-standard auto and motorcycle; SR-22/DUI/foreign/youthful; delivery & rideshare endorsements. SSPL has no binding authority.$c$, $c$Auto (monoline): Limits 30/60 or 50/100; Physical Damage; Named Non-Owner
Motorcycle (monoline): Standard to Preferred; Cruising & Touring Bikes; Trikes and Conversion Kits; Mopeds and Scooters; Standard Street Bikes$c$, $c$Auto: Non-Standard Auto$c$, $c$Auto:
- More than 21 points in total [per operator]
- State specific: NC — No Liability Only$c$, $c$- SSPL has no binding authority; must be issued day before desired effective date
- Competitive pricing for SR22s, DUIs, foreign operators, minimum limits, youthful drivers, no prior insurance, expired/suspended licenses, out-of-state licenses
- Payment: Paid in Full, 6/3/1-month billing; auto bill pay via EFT (checking, savings, credit card); Visa & Mastercard
- eSignature; Ride share (Uber, Lyft, etc.); Delivery endorsements (Instacart, DoorDash, etc.)$c$, 90)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$ePremium$c$, $c$epremium$c$, $c$not_started$c$, ARRAY[$c$Renters$c$]::text[], ARRAY[]::text[], $c$Monoline renters (HO4). No credit, no background checks, no CLUE.$c$, $c$Monoline Renter's HO4:
- Contents coverage up to $75K; Scheduled Personal Property
- Personal Liability up to $300K; Loss of Use (20% of Coverage C)
- No restricted animal breeds ($10K cap on animal liability)
- Endorsements available for Water Backup and Identity Fraud$c$, $c$N/A$c$, $c$N/A$c$, $c$- No use of credit
- No background checks
- No use of CLUE$c$, 100)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Foremost Signature$c$, $c$foremost-signature$c$, $c$not_started$c$, ARRAY[$c$Home$c$,$c$Auto (Standard)$c$,$c$Condo$c$,$c$Renters$c$,$c$Landlord$c$,$c$Umbrella/Excess$c$]::text[], ARRAY[]::text[], $c$Preferred–standard home & auto (package, or monoline in select states); condo, renters, landlord, and umbrella.$c$, $c$Home:
- Package; monoline available: AL AZ IA ME NH NM OK SD TN TX VT WV
- Primary Home; Secondary/Seasonal (state specific — monoline or supporting auto/home; monoline needs no losses within 5 years)
Auto:
- Package; monoline available: AL IA ME MS NE NH NM SD TN TX VT WV WY
All Other Lines:
- Umbrella (underlying auto/home required); Landlord (requires supporting auto/home)$c$, $c$Home:
- $100K Coverage A Min (Value Plus, Enhanced Plus); $250K Min (GrandProtect); $1.5M Coverage A Max
Home Secondary/Seasonal: $100K Min - $500K Max
Condo/Condo Landlord/Renters: $25K Coverage C Min; $250K Coverage C Max; $300K Coverage A Max (Condo)
Landlord: $100K Coverage A Min - $500K Max
Auto: Foremost ARS Auto non-package must be 6-month term; annual available if package under Combo or GrandProtect$c$, $c$- 4 dwelling units/families
- Properties in name of business, LLC, LP, Corporation, or land trust
- Home-based business [incidental only]; home daycare, assisted living, nursing/group home
- Properties rented > 30 days; Landlord — short-term/weekly/seasonal rentals
- Farming as primary income
- Prior losses: 3+ in 5 years; 2+ same peril in 5 years; 1+ liability or home fire loss in 5 years; Landlord — 2+ in 5 years
- Shingle roofs over 15 yrs or with visible repair/replacement; flat roofs over 10 yrs or any flat roof when YOC > 20 yrs
- Major systems not modernized (no circuit breakers/active knob & tube; no galvanized/polybutylene pipes)
- Unfenced pool; Landlord — no pool
- Dogs with prior bite history or on ineligible dog list$c$, $c$- Preferred to Standard risks; bundle discounts for home/auto
- Quote honoring: monoline auto 7 days; monoline home/umbrella 30 days; bundled (all LOB incl. auto) 30 days
- Auto 6 or 12-month terms
- Coverage levels: Value Plus (Basic), Enhanced Plus (Better), GrandProtect (Best/HO5)
- Home optional: sewer/drain/sump backup, builder's risk, code upgrade & demolition, earthquake, home systems (equipment breakdown & service line), personal injury
- Scheduled personal property (items > $25,000 require appraisal)
- Auto inclusions: ID theft resolution, accident forgiveness, enhanced rental, all household vehicles regardless of title, limited Mexico coverage
- Auto optional: up to $1M liability, child safety seat replacement, new vehicle replacement, loan/lease gap, OEM, diminishing deductible, worldwide liability (auto w/ GrandProtect), rideshare (Uber/Lyft), local food delivery
- Umbrella: $1/2/3/5/10M options ($1-$2M binding authority); optional UM/UIM$c$, 110)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Gainsco$c$, $c$gainsco$c$, $c$not_started$c$, ARRAY[$c$Auto (Non-Standard)$c$]::text[], ARRAY[]::text[], $c$Non-standard auto; SR-22/DUI/foreign/youthful; liability-only any vehicle age, phys dam to 30 yrs & salvage titles. SSPL has no binding authority.$c$, $c$Auto (monoline):
- Liability Only; any vehicle age accepted
- Physical Damage; up to 30 years and available for salvage titles
- Named Non-Owner$c$, $c$Auto: Non-standard; minimum limits in all states except PA (PA has special binding process for 50/100 — see guide)$c$, $c$Auto:
- More than 21 points in total [per operator]
- Ride share (Uber, Lyft, etc.)$c$, $c$- SSPL has no binding authority; must be issued day before desired effective date
- Competitive pricing for SR22s, DUIs, foreign operators, minimum limits, youthful drivers, no prior insurance (Prior Discount for up to 60-day lapse), expired/suspended licenses
- Payment: Paid in Full and 6-month policies; downpayment/plans vary by state; auto bill pay via EFT (checking, savings, debit or credit); Visa & Mastercard
- eSignature$c$, 120)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Homeowners of America$c$, $c$homeowners-of-america$c$, $c$not_started$c$, ARRAY[$c$Home$c$,$c$Dwelling Fire$c$,$c$Landlord$c$]::text[], ARRAY[]::text[], $c$Middle-market homeowners (newer homes, ~$400–450K replacement cost), owner-occupied; dwelling fire / landlord; pools & solar OK.$c$, $c$Homeowners:
- Owner-occupied primary residences; new properties 0–5 years old are a key appetite
- Homes up to 100 years old (over 50 with renovations); pride of ownership; preferred risks with good credit
- Homes with pools; homes with solar panels; new homebuyers / refinancing
- Avg replacement cost target ~$400,000–$450,000
Dwelling Fire:
- Townhomes; duplexes; landlord/rental properties; investor-owned dwellings within UW tolerance
Preferred: middle market, strong insured engagement; discounts (not all states): Accredited Builder, Advanced Shopper, Companion Product, New Purchase, Alarm/Security, Claim-Free, Wind Mitigation$c$, $c$- Well-maintained properties; favorable loss history; good credit; pride of ownership
Homeowners eligibility: up to 100 years old; standard construction; maintained; acceptable RCE; eligible occupancy
Dwelling Fire eligibility: acceptable condition; standard rental exposure; no major structural concerns; acceptable vacancy history
Loss history: limited prior losses; minimal water losses; minimal frequency/severity$c$, $c$Homeowners:
- Under construction or major renovation; aluminum/knob & tube/dangerous wiring
- Secondary, seasonal, or short-term occupancy; more than 2 units
- Open foundation or on stilts; detached structures over 700 sq ft
- Mobile or modular homes; barndominiums or tiny homes
Dwelling Fire:
- Poor condition or lack of maintenance; farm or daycare exposure; secondary/seasonal; open foundation or vacant; lapse > 30 days
Unacceptable loss history: 2+ water in 3 yrs; 3+ losses in 3 yrs; 2+ fire in 5 yrs; 2+ theft/disappearance in 5 yrs; any fire liability/med pay/disappearance in 5 yrs; 2+ non-weather in 3 yrs; losses > $50,000 in 3 yrs; any open claims
Catastrophe: 2+ non-weather in 3 yrs; any fire or flood loss in 3 yrs$c$, $c$- HOA is strongest in middle-market homeowners with newer homes as core appetite
- Best-fit risks are insureds who actively maintain and improve their homes
- Leverage available discounts to improve competitiveness
- Focus on new business and households shopping current carriers
- HOA/Porch emphasizes preventative maintenance & homeowner engagement$c$, 130)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Kemper Auto$c$, $c$kemper-auto$c$, $c$not_started$c$, ARRAY[$c$Auto (Non-Standard)$c$]::text[], ARRAY[]::text[], $c$Non-standard auto; foreign / no-US-license OK; SR-22/DUI/youthful; NNO convertible by endorsing a car.$c$, $c$Auto (monoline):
- Liability Only; Physical Damage; Named Non-Owner
- Foreign license, no US license OK$c$, $c$Auto: Non-Standard Auto$c$, $c$Auto: Ride Share (Uber, Lyft, etc.)$c$, $c$- Competitive pricing for SR22s, DUIs, foreign operators, youthful drivers, no prior insurance
- NNO policy can be converted by endorsing a car — no need to re-write
- Expired and suspended licenses accepted
- Payment: Paid in Full, 12 or 6-month terms (depends on state); auto bill pay via EFT (checking, savings, or credit card); Visa & Mastercard
- eSignature$c$, 140)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$KleeCo Private Client$c$, $c$kleeco-private-client$c$, $c$not_started$c$, ARRAY[$c$Home$c$,$c$Auto (Standard)$c$,$c$Umbrella/Excess$c$,$c$Valuables$c$,$c$Watercraft$c$,$c$Specialty$c$]::text[], ARRAY[]::text[], $c$High-net-worth (AIG Private Client via Bob Klee) — home $1.5M+ with 2 supporting lines; collector autos, yachts, valuables, specialty.$c$, $c$Home: Must include at least 2 additional lines: auto, valuables, umbrella/excess
Auto: No monoline (collector cars $1.5M+ considered in place of auto); high-end luxury, antique, high performance; agreed value, OEM parts, $15,000 car rental
Umbrella/Excess: $1M-$100M; UM/UIM $1M-$10M
Valuables: jewelry, fine arts, wine, guns, books, coins, memorabilia, collections
Specialty: Home Course of Construction (needs supporting LOB), Flood, Earthquake, Builders Risk, EPLI, D&O non-profit
Boats/Recreational: various watercraft incl. yachts; RV, ATV, Golf Carts, Motorcycles$c$, $c$Home: Minimum Coverage A $1.5M+ (higher minimum in CAT-prone areas); Condo/Renters $250K-$500K (depends on state)
Auto: No monoline; must support the primary home (exception: car collections $1.5M+)
Watercraft: monoline acceptable; written with supporting lines
State-specific: CA/FL/TX $5M minimum Total Insured Value incl. valuables and multiple homes$c$, $c$- More than 1 property loss (disclose all losses — subject to UW review; water claim requires water shut-off valve)
- Prior lapse in coverage$c$, $c$- KleeCo Private Client is a broker-partnership with Smart Choice / Smart Start Personal Lines offering AIG Private Client solutions for high-net-worth clients
- Led by Bob Klee — nearly 40 years of insurance expertise, 12+ years focused on high-net-worth$c$, 150)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Lamar$c$, $c$lamar$c$, $c$not_started$c$, ARRAY[$c$Auto (Standard)$c$,$c$Auto (Non-Standard)$c$]::text[], ARRAY[]::text[], $c$Monoline standard & non-standard auto; SR-22; state minimum–100/300; named non-owner. A Producers National company (Stonegate/Unique/Lamar).$c$, $c$Auto (monoline):
- 6-month term available; 12-month only for SR-22
- Liability limits: State Minimum – 100/300
- Physical Damage available$c$, $c$Standard Auto; Non-Standard Auto$c$, $c$- Multiple Stonegate/Unique/Lamar policies in same household
- Prior Stonegate/Unique/Lamar policies non-renewed in past 36 months
- Drivers over incident limits: >3 non-chargeable in 36 mo; >2 at-fault in 36 mo; >2 major in 36 mo; >1 DUI/drug in 36 mo; >4 combined violations in 36 mo
- No valid US or foreign license/learner permit
- Valid license from NY or NJ
- Revoked/suspended license (exception: proof of financial responsibility)
- Spouses living in separate households
- TNC / Uber / Lyft
- Vehicles primarily garaged in CA, DC, FL, HI, KY, MA, MI, MO, NJ, NY, WV, or outside US$c$, $c$- Liability only acceptable; comp & collision must be written in tandem
- AD&D, Replacement Cost Coverage, Custom Equipment, OEM options
- Accident Forgiveness and Diminishing Deductible options
- Accept SR-22 (state minimum limits only); named non-owner offered
- Proof of prior required when prior carrier can't be validated in quote system
- Must cover at least one rated named insured; vehicles garaged in resident state 10+ months/year
- Standard vehicles only (no commercial trucks; no antique/classic/custom/motorhome/van conversion/camper)
- Salvage title acceptable for liability only; vehicles > 25 yrs no phys dam; > 30 yrs not acceptable
- Payment: Credit/Debit (Visa, Amex, Discover, Mastercard), EFT; down payment required for new business; recurring payment required$c$, 160)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Lemonade$c$, $c$lemonade$c$, $c$not_started$c$, ARRAY[$c$Home$c$,$c$Condo$c$,$c$Renters$c$,$c$Auto (Standard)$c$]::text[], ARRAY[]::text[], $c$Digital monoline home, condo & renters (and auto in IL/TN); app/email required; must bind future-dated.$c$, $c$Home: Monoline Primary/Single Family; Monoline Secondary/Seasonal
All Other Lines:
- Monoline Auto (IL, TN)
- Monoline Condo
- Monoline Renters (AZ, CO, CT, DC, GA, IA, IL, IN, MA, MD, MI, MO, NJ, NV, NY, OH, OK, OR, PA, RI, TN, TX, VA, WA, WI) — renters & condo submitted via Manual Quote Process (not on comparative rater)$c$, $c$Home: $125K Coverage A Min; $1.5M Coverage A Max
Condo: $30K Coverage A Min / $20K Coverage C Min; $1.5M Coverage A Max / $250K Coverage C Max$c$, $c$- No email or won't download the carrier app
- Lapse in coverage (unless first-time home buyer); prior cancellations/non-renewals in last 5 years
- Vacant, under construction/renovation, foreclosure, for sale
- Mobile/manufactured, log, trailers, house trailers, modular, farms; container homes; earth homes
- LLC ownership (unless for tax purposes only); home-based business
- Short-term rentals < 12 months; no Airbnb; more than one family per unit
- State/National Registry of Historic Places; farming/ranching
- No smoke detector; flat roofs (hail states) or poor-condition roofs; roofs < 5 yrs life expectancy
- Water heaters older than 10 years; no thermostatically controlled heating; PC 9, 10
- Overhanging trees; pools/trampolines/hot tubs/playground in disrepair or unfenced; no diving boards/slides
- More than 2 mortgages; dogs with bite history or on breed list; no exotic pets
- Home over/near water or open foundation; buried oil/fuel tanks
- Claims: no more than 2, no open/unresolved; no paid theft or mysterious disappearance
- Coastal/CAT restrictions (coastal waters, wildfire/brushfire, flood-prone, earthquake)$c$, $c$- Must provide client's valid email for quote/binding; must bind with future effective date (cannot bind same day)
- HO3 (Home) & HO6 (Condo) are the standard forms
- Exclusions: pool liability (buyback in some states), trampoline liability, high-risk breed liability
- All policies include Replacement Cost Dwelling & Contents (no ACV)
- Optional: Earthquake, Extended Replacement Cost, Mold, Above-ground Oil Tank, Personal Injury, Water Backup, Pool Liability, Loss Assessment, Ordinance or Law, Mine Subsidence
- Claim history based on customer, not property; $1M liability available; no acreage limitation (no farms)
- Dogs on breed list excluded from coverage; scheduled personal property available; quotes expire after 90 days
- Roof Payment Schedule may apply for wind/hail based on age$c$, 170)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Liberty Mutual$c$, $c$liberty-mutual$c$, $c$not_started$c$, ARRAY[$c$Home$c$,$c$Auto (Standard)$c$,$c$Condo$c$,$c$Renters$c$,$c$Dwelling Fire$c$,$c$Umbrella/Excess$c$,$c$Powersports$c$]::text[], ARRAY[]::text[], $c$Home (auto required) & monoline auto; manufactured homes in many states; boat/motorcycle/golf cart/snowmobile specialty. SSPL binding up to 10 days.$c$, $c$Home:
- Auto Required
- Manufactured homes — AZ, AR, CO, ID, IL, IN, IA, KS, KY, LA, MA, MN, MO, NE, NH, NV, NM, NY, OH, PA, TN, UT, VT, VA, WA, WI (subject to age restrictions); Auto Required
Auto: Monoline available in most states
All Other Lines: Monoline Specialty (Boat/Motorcycle/Golf Cart/Snowmobiles); Umbrella/Dwelling Fire must have supporting LOB$c$, $c$Home:
- $125K Coverage A Min; $25K Coverage C Min on renters & condos
- Coverage Level: New Quality-Plus or higher (or state equivalent); Package
Auto:
- Monoline available in most states; annual term; comp on at least one vehicle
- Prior carrier must be Standard/Preferred; current BI/PD limits must be 50/100
- Deductibles: $1,000 Collision, $500 Comprehensive; Coverage Level: Enhanced or higher; Telematics recommended$c$, $c$Home:
- Woodstove not professionally installed
- Asphalt roof not updated in 15 years
- Home Share (Airbnb, VRBO, etc.)
- Trusts where grantor is deceased
- No lapse in coverage or prior coverage (unless new home purchase)
Auto:
- Prior carrier is Non-Standard
- Less than 6 months continuous coverage (state dependent)
- No consecutive/prior coverage$c$, $c$- SSPL has binding authority up to 10 days
- ITV increases up to 125%
- eSign preferred (email required); if not chosen, send to smartstartpl@smartchoiceagents.com within 5 business days of issuance
- Education & occupation are critical rating factors
- 4-vehicle maximum per auto policy (5th+ on separate policy); auto value max $130K
- Ride Share (Uber, Lyft, etc.)
- Payment: Paid in Full, Direct Bill, RCC, EFT (Visa, Mastercard, Amex, Discover; valid email required for RCC)$c$, 180)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Mercury$c$, $c$mercury$c$, $c$not_started$c$, ARRAY[$c$Home$c$,$c$Condo$c$,$c$Renters$c$,$c$Auto (Standard)$c$,$c$Umbrella/Excess$c$,$c$Landlord$c$]::text[], ARRAY[]::text[], $c$Package home + auto (monoline accepted); preferred autos and pride-of-ownership homes; umbrella to $5M. No BOR.$c$, $c$Available Products: Homeowners; Condo Owners; Renters; Preferred Auto; Umbrella ($1M-$5M, UM/UIM $1M); Landlord
Target Market: stable, prior insurance, non-shopper, responsible; package (home + auto focus, monoline accepted); good driving record; professionals; own home / pride of ownership; newer / recently updated homes$c$, $c$Private Passenger Auto (rating accuracy):
- Household members must be Rated/Excluded/Listed (all ages & license statuses)
- Occupations (type, employer/school name & address); vehicle use (pleasure/commute/business/artisan)
- Mileage: annual + odometer (REALDRIVE app verifies); business use if multiple work addresses
- Uber/Lyft max 20 hrs/wk; license types (non-US = Foreign yes / International no); permit drivers added (no charge if <19)
- REALDRIVE required (annual mileage via telematics)
Discounts requiring proof: AAA Membership, Good Student, Group Discount (all others no proof)
Homeowners:
- Max 1 prior claim in last 5 yrs (no prior water claims)
- Homes > $3M max ($1M+ needs UW approval; high value: deductible >= $2,500 and Platinum Package)
- Secondary homes require supporting primary
- Roof: shingle >25 yrs Do Not Submit; shingle 15-25 yrs roof endorsement applies
- Dogs: mixed breeds must disclose full breed; photos for binding: front, back, both sides (roof visible)$c$, $c$Homeowners:
- No prior insurance / lapse; roof in poor condition (aerial verified); manufactured homes; major systems not updated in 50 yrs; short-term rentals; homes < 1/2 mile to sea/bay/tidal/sound; vacant; unfenced pool/trampoline; PC10/10W; dog on ineligible list / bite history / vicious propensity; LLC/Corp/Corp Trust ownership; log homes; underground oil tank; asbestos siding/shingles; flat roof HO-3; zoo/exotic animals; fireline/brush risks; farming/ranching >10 acres or >2 hoofed animals
Auto:
- No prior insurance / lapse; Uber Eats / DoorDash; vehicles cost new > $100K; high performance/horsepower; driver/vehicle ratio > 1:1$c$, $c$Homeowners:
- Coverage packages: Platinum, Titanium, Green Home
- Endorsements: Service Line, Home Systems, Home Cyber Security
- Additional Replacement Cost: 25% / 50% options; new purchases don't require prior insurance
- Inspections: all homes exterior; >50 yrs exterior + interior; Flyreel DIY inspection app available
UW approval required: year built < 1940; historical registry; Coverage A > $1M
General: NO BOR accepted$c$, 190)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$National General (Allstate)$c$, $c$national-general-allstate$c$, $c$not_started$c$, ARRAY[$c$Home$c$,$c$Auto (Standard)$c$,$c$Umbrella/Excess$c$,$c$Condo$c$,$c$Renters$c$]::text[], ARRAY[]::text[], $c$Monoline or package home & auto (50/100 min, standard/preferred prior); umbrella with auto + home. SSPL 5-day binding.$c$, $c$Home: Monoline or Package (subject to individual risk assessment & state guidelines)
Auto: Monoline or Package (subject to risk assessment & state guidelines); 50/100 minimum quoted limits
All Other Lines: Umbrella — must have Auto and Home LOBs$c$, $c$Home: Coverage A $100k Min - $1.5M Max; Coverage C $25k Min for Renters/Condos
Auto: 50/100 BI limits minimum; prior carrier Standard/Preferred; comp on at least one vehicle$c$, $c$Home:
- Two or more losses or water claim; asphalt roof not updated in 15 yrs; wood roof; historical registry; wood-burning stove; PC 10; open foundation (piers, stilts, wharves, jetties, pilings)
Auto:
- Less than 6 months continuous coverage; prior limits below 50/100; prior carrier non-standard; no consecutive/prior coverage; named insured licensed < 3 yrs; foreign license; SR-22 within 5 yrs; extended non-owned auto; total vehicles exceed operators by more than one$c$, $c$- SSPL has 5-day binding authority; ITV can increase to 150% (varies by state)
- Email required; e-signature required for NB application & documents
- Ride Share (Uber, Lyft); up to 4-family homes (varies by state); Home Share (Airbnb, VRBO)
- Payment: Paid in Full, Direct Bill, EFT, RCC (Visa, Mastercard, Discover & Amex)
- No AORs$c$, 200)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$National General Insurance$c$, $c$national-general-insurance$c$, $c$not_started$c$, ARRAY[$c$Auto (Standard)$c$,$c$Auto (Non-Standard)$c$,$c$Motorcycle$c$]::text[], ARRAY[]::text[], $c$Monoline standard & non-standard auto and motorcycle; state min/liability-only/SR-22/lapsed/foreign DLN; retained DWI pricing. Must issue day before effective date.$c$, $c$Auto: Monoline Auto; Monoline Motorcycle$c$, $c$Auto: Standard Auto; Non-Standard Auto$c$, $c$N/A (Do not submit if Ride Share — Uber, Lyft, etc.)$c$, $c$- Must be issued day before desired effective date
- NB applications due to smartstartpl@smartchoiceagents.com within 5 business days from issuance
- Accept state minimums / liability only / SR-22 / lapsed coverage / no prior / suspended / foreign DLNs
- Retained pricing for DWI convictions; named non-owner policies
- Do not submit if Ride Share (Uber, Lyft, etc.)
- Payment: Paid in Full, Direct Bill, EFT (Visa & Mastercard)

Plan Codes (State / Product / Code):
AL Personal Auto M | AL Value M6 | AR Value M6 | AZ Value M, M6 | CA Summit 2C | CA Value 2D | CA Personal Auto M | CO Value M6 | CT Value G5 | DE Value M | FL Personal Auto M6 | GA Value M6 | IA Value M6 | ID Personal Auto M6 | IL Value M6 | IN Value M6 | KS Personal Auto M6 | KY Value M6 | LA Advantage R5 | MD Advantage M | MD Value M6 | ME Personal Auto M6 | MS Personal Auto M | MS Value M6 | MN Value M6 | NC All M | ND Value M6 | NE Personal Auto M6 | NH Personal Auto M | NM Personal Auto M6 | OH Advantage G5 | OH Value M6 | OK Personal Auto M | OK Value M6 | OR Value M | PA Value M6 | RI Personal Auto M | SC Value M6 | SC Advantage R5 | SD Personal Auto M6 | TN Personal Auto M | TN Value M6 | TX Personal Auto 3C | UT Value M6 | VA Personal Auto G5 | WA Personal Auto M | WI Personal Auto M6 | WV Personal Auto M | WY Value M6$c$, 210)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Nationwide$c$, $c$nationwide$c$, $c$not_started$c$, ARRAY[$c$Home$c$,$c$Condo$c$,$c$Renters$c$,$c$Auto (Standard)$c$,$c$Umbrella/Excess$c$,$c$Powersports$c$]::text[], ARRAY[]::text[], $c$Home (auto required) with SmartHome water device & telematics auto; condo/tenant/secondary; powersports & umbrella. FL property not available.$c$, $c$Home:
- Auto Required; available with auto: Condo, Tenant, Seasonal & Secondary Home/Condo (primary required)
- MS Home not available (condo & tenant available); FL property not available
Auto: Telematics offerings; self-service options
All Other Lines: Umbrella (underlying policies required); Powersports (monoline or package)$c$, $c$Home:
- $1.5M Max Coverage A; 100% ITV per reconstruction tool
- $300K Max Coverage A&C for Condo; $200K Max Coverage C for Renters; up to 4 units
Auto: 50/100 minimum; no lapse; proof of 6 months continuous coverage$c$, $c$Home:
- Prior fire or liability claims in prior 5 years; not owner occupied; PC 10; vacant or under construction; short-term rental (Airbnb, VRBO); historic registry; mobile/manufactured; geodesic, log, earth/berm; unique/hard-to-replace structures; poor condition/upkeep; tree limbs on roof/siding; unsecured pool/trampoline; dangerous/exotic animals; dogs with bite/attack history or trained guard dogs
Auto:
- No prior coverage; less than 6 months continuous; single-vehicle liability only; no Uber/Lyft rideshare$c$, $c$Home (vary by state):
- Smart Home: free water-detection device, discount up to 10%
- Dwelling Replacement Options (150%, 200% Guaranteed RC); Valuables Plus (scheduled personal property; items $25,000+ need appraisal < 5 yrs; boat dock option)
- Better Roof Replacement; Brand New Belongings; Equipment Breakdown; Service Line; ID Theft/Fraud Expense; Protection Boost; Earthquake
- Payment: Monthly or Pay in Full, EFT, Credit/Bank Card, Check, Money Order, Escrow Bill; recommend $2,500 deductible
Auto:
- SmartRide telematics; Advanced Quote Discount (8+ days); Vanishing Deductibles; Accident & Minor Violation Forgiveness; New Car Replacement; Loan/Lease Gap; Roadside; 6-month or annual; recommend $1,000 deductible$c$, 220)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Orion180$c$, $c$orion180$c$, $c$not_started$c$, ARRAY[$c$Home$c$]::text[], ARRAY[$c$AL$c$,$c$AZ$c$,$c$GA$c$,$c$IN$c$,$c$MS$c$,$c$NC$c$,$c$OH$c$,$c$SC$c$,$c$CA$c$,$c$FL$c$,$c$MA$c$,$c$TX$c$]::text[], $c$Owner-occupied HO3 (admitted inland & non-admitted coastal); new FLEX Home product in CA/FL/MA/TX. Modular & secondary/seasonal OK.$c$, $c$Preferred Homeowners (monoline, owner occupied): single family; secondary/seasonal; modular
Admitted Product – Inland: AL AZ GA IN MS NC OH
Non-Admitted Product – Coastal: AL GA MS NC SC (barrier island restrictions in AL, GA, MS, NC)
New FLEX Home product: CA FL MA TX [Non-Admitted] — Flex Perils, Roof Coverage Options, Co-Pay Options, Deductible Options (non-weather & weather/wildfire), Premium Protection, Claim Free Participation Bonus$c$, $c$- Coverage Form: HO3 / Special
- Coverage A: Min $200,000 – Max $1,000,000 (100% ITV)
- Coverage A (FL): $300,000 - $2,000,000; (CA/MA): $300,000 - $3,000,000; (TX): $350,000 - $2,000,000
- Homes 30+ yrs must have electrical, plumbing, HVAC, roof in good condition; 30+ yrs applies $10,000 Limited Water Damage Limitation
- Non-Admitted: all roofs acceptable condition or elect Roof Damage Exclusion
- Admitted AL/MS outdated roofs ACV: Metal 26+ yrs, Slate/Tile 21+ yrs, Composition & other 16+ yrs
- Admitted IN: Roof Payment Schedule EN mandatory on NB for shingle roofs 16+ yrs
- Foundations: slab, crawl space 3 ft or less, pilings, piers, stilts
- Plumbing exclusions: PEX (pre-2006), cast iron, polybutylene, galvanized (Admitted: water damage limited $10,000; Non-admitted: not covered)
- Water heaters in attic not acceptable Admitted (tankless OK); Non-admitted limited $10,000; screened enclosures excluded (non-admitted); aluminum/metal siding needs Cosmetic Hail Loss Limitation (non-admitted)
- Excluded: golf carts, diving boards/pool slides/trampolines, pool/hot tub liability (buyback w/ 4ft fence), animal liability, renewable energy/solar
- Credit scoring: Admitted YES, Non-admitted NO
- Age of home: Admitted no restriction (must be updated); Non-admitted no homes pre-1900 (must be updated)$c$, $c$- No rental or home sharing (Airbnb, VRBO); PC 10
- Vacant, unoccupied for sale > 30 days, or under construction
- Corporation/LLC/partnership/estate ownership; commercial exposure on/adjacent
- Space heaters or woodburning stoves as primary heat; water heaters in attic (tankless OK)
- Electrical: fuses, knob & tube, aluminum, double-tapped, Federal Pacific, Zinsco/GTE Sylvania, Challenger
- Asbestos; more than 5 acres; livestock/farming; historical significance; daycare
- Mobile/manufactured, log, trailer/house trailers; unconventional construction; open foundations; over water/mountainside/cliff
- Existing damage/poor condition; empty or unmaintained pools/hot tubs/spas
- Animals with bite history/aggressive behavior; burglar bars without inside release; overhanging/dead/dying trees$c$, $c$- Proof of prior not required; quotes valid 60 days; can quote/bind up to 60 days in advance
- Townhomes acceptable (firewall + proof for YOC prior to 2000)
- Up to 2 claims in past 3 years (Act of God not counted); no more than 1 liability, fire, or 2 property claims; no open claims
- Multiple deductible options (AOP and Wind/Hail); optional coverages; multiple discounts (admitted & non-admitted, docs may be required); payment plans; trusts acceptable
- Property inspection within 30 days of policy term effective date for homes requiring it$c$, 230)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Progressive$c$, $c$progressive$c$, $c$not_started$c$, ARRAY[$c$Auto (Standard)$c$,$c$Motorcycle$c$,$c$Powersports$c$,$c$Watercraft$c$]::text[], ARRAY[]::text[], $c$Monoline auto (closed in a few states) plus rec lines: ATV/UTV, golf cart, motorcycle, RV, snowmobile, watercraft. Snapshot telematics.$c$, $c$Monoline Auto (Closed: MA, ME, MI, ND, RI, UT, VT)
Rec Lines: ATV/UTV; Golf Cart; Motorcycle; RV; Snowmobile; Watercraft$c$, $c$- Signed applications/forms by eSignature completed by end of business day
- All household members listed (licensed or not): college students, title owners, any regular operator; rated or excluded
- Minimum comprehensive & collision deductibles: $750$c$, $c$- Vehicles principally garaged out of state; commercial auto types
- Pick-up/vans/utility with GVWR > 14,000 lbs
- Comprehensive only (liability required on at least one vehicle)
- Vehicle value > $150,000
- AOR$c$, $c$- Top discounts/factors: Snapshot telematics (15% participation credit, up to 30-50% by state), Paid in Full, EFT, Paperless
- Advanced Shopping Discount (quote effective date 7+ days out)
- Verify: SSN, prior carrier/BI limits, annual miles (proof may be required), length of ownership, employment/occupation, education, home/condo ownership
- Insured/driver names match DL; if at mailing address < 2 months provide prior address; accurate VIN; garaging zip (50%+)
- Rideshare/TNC for Uber/Lyft; named non-owner available; foreign & international licenses acceptable
- Optional: Progressive Vehicle Protection (warranty), Accident Forgiveness, Deductible Savings Bank$c$, 240)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Steadily$c$, $c$steadily$c$, $c$not_started$c$, ARRAY[$c$Dwelling Fire$c$,$c$Landlord$c$,$c$Condo$c$]::text[], ARRAY[]::text[], $c$Landlord / dwelling fire (DP1/DP3), 1–4 family rentals incl. short-term; multi-location schedules; fast investor binding.$c$, $c$Dwelling Fire:
- DP1 (ACV or Repair Cost Valuation — not in CA)
- DP3 (RCV or Extended); DP3 Condo
- DIC (CA; restrictions apply): restricted counties verified at quoting; elevation above 3,000 ft; wildfire exposure; must be rental (no primary home)$c$, $c$- Up to $1.5M Coverage A (Dwelling)
- Up to $350K Coverage A (Condo)
- $1M Premises Liability$c$, $c$- Apartments (5+ units); risks with/attached to commercial exposure
- Mobile/manufactured; under construction & heavy renovation
- Poor property & roof conditions; vacancy (60+ days)$c$, $c$- 1-4 family rental dwellings; up to 100 years old (subject to roof guidelines); >101 yrs requires approval + proof of updates (electrical/plumbing/HVAC within 30 yrs pre-1940; AZ & CA pre-1940 ineligible; MN pre-1960 ineligible)
- Individuals, LLCs, Corporations, Partnerships; multi-locations
- Airbnb, VRBO, short-term & seasonal rentals accepted
- All risks inspected within 30 days (exterior all; interior risk dependent)
- Wildfire & coastal (1 mile from coast) ineligible (X-Wind coastal policies)
- Renovation policies (Fix-and-Rent / Fix-and-Flip)
- All Direct Bill: 10% down credit card/ACH (no fees); mortgagee
- Additional coverage: HOA Fines ($500/$1,000, non-admitted states), Service Line/Equipment Breakdown (admitted), Extended Replacement Cost 10% & 25%, Ordinance or Law
- Accepts multiple locations/property schedules with certain restrictions$c$, 250)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Swyfft$c$, $c$swyfft$c$, $c$not_started$c$, ARRAY[$c$Home$c$]::text[], ARRAY[$c$AL$c$,$c$MA$c$,$c$TX$c$,$c$CA$c$,$c$FL$c$,$c$LA$c$,$c$MS$c$,$c$NC$c$,$c$NJ$c$,$c$SC$c$]::text[], $c$Owner-occupied homeowners admitted & non-admitted incl. coastal; annual & short-term rentals qualify on the non-admitted product.$c$, $c$Preferred Homeowners (monoline, owner occupied); Secondary/Seasonal (owner occupied, winterized if dormant)
Admitted Product: AL (Baldwin & Mobile only), MA, TX (Tier 1, Tier 2 & contiguous counties)
Non-Admitted Product: AL CA FL LA MA MS NC NJ SC TX (CA open counties: Kern, Los Angeles, Sacramento, San Diego, San Joaquin, San Bernardino)
Non-admitted also qualifies: full-time annual rental (lease required); short-term rental < 21 weeks (owner must occupy during calendar year)$c$, $c$- Coverage A: Min $125,000 – Max $2,000,000 (100% ITV)
- No age of home restrictions (NJ: 100 years or newer)
- Max roof age 30 years (other limits by roof type & location)
- Pools acceptable with pool cage or 4' permanent fence + self-latching gate; diving boards/slides/trampolines eligible
- Pool cages/screen enclosures/carports excluded for hurricane (optional buyback)
- Animal Liability $100,000 (NJ $50,000); ineligible dog list (risk eligible, animal liability excluded)
- CA: Escape of Water exclusion if home unoccupied > 10 days without plumbing turned off
- Full-time annual rentals require copy of annual lease$c$, $c$Occupancy: vacant, under construction, for sale, foreclosure; name of Estate or Business; more than two mortgages; seasonal/secondary non-owner occupied
Plumbing: water heaters in attic 8+ yrs; living areas 12+ yrs; non-living areas 25+ yrs
Electrical: homes without central heat source
Structure: disrepair/existing damage (incl. outbuildings); large overhanging limbs; roofs less than good condition; Tesla solar roofs/batteries/parts; asbestos/Masonite/EIFS/synthetic stucco siding; any part over water; barndominiums/mobile/manufactured; homes less than 800 ft; historical homes; fraternity/sorority houses
Claims: AL/NJ no more than 1 non-weather loss in 3 yrs; MA no more than 4 non-weather in 3 yrs; any open claims; any prior sinkhole; prior liability/fire loss requires UW approval$c$, $c$- All properties inspected (exterior & interior); inspected annually, $100 billed at renewal
- Wind Deductible Buy Back available; optional coverages; multiple discounts
- Non-admitted home policies subject to 25% Earned Premium; signed applications required
- Flexible pay plans (no premium financing); prior lapse / non-renewed/cancelled requires UW approval; Trust requires UW approval$c$, 260)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Trexis$c$, $c$trexis$c$, $c$not_started$c$, ARRAY[$c$Auto (Non-Standard)$c$]::text[], ARRAY[$c$AL$c$,$c$AZ$c$,$c$AR$c$,$c$CO$c$,$c$GA$c$,$c$IN$c$,$c$KY$c$,$c$MS$c$,$c$NV$c$,$c$OH$c$,$c$SC$c$,$c$TN$c$,$c$TX$c$,$c$VA$c$]::text[], $c$Non-standard & scored auto (Trexis / Trexis One); SR-22/DUI/foreign; entire households must be rated. Alfa/Trexis group.$c$, $c$Monoline Auto:
- AL AZ CO MS NV SC: liability up to 50/100/50
- AR GA IN KY OH TN TX VA: up to 100/300/100 (requires: PNI 21+, drivers no more than 5 points in prior 36 months, one-month-down EFT acceptable; direct bill requires more than one month down)
- Terms: 6-mo (AL AZ AR CO GA MS NV SC); 3/6/12-mo (IN); 3/6-mo (TX); 6/12-mo (KY OH TN VA)
- Comp/Collision deductibles $250-$1,000; Accidental Death offered; Non-Owner use$c$, $c$- Signed applications/forms by eSignature (within 15 days or policy cancelled)
- All drivers 14/15+ must be rated or excluded (licensed or not); all regular/frequent operators rated or excluded
- Entire household on single policy$c$, $c$- Not permanent resident of the state; vehicles garaged out of state
- Permanently suspended/revoked licenses (regaining via financial responsibility filing OK)
- Minor/under 18 as Named Insured
- Any household operator registered in Ridesharing/TNC in past 3 years
- Convicted of insurance fraud; antique/classic
- Commercial use (livery, for-hire, Lyft/Uber/DoorDash/Uber Eats/Pizza, delivery, hauling, landscaping)
- Vehicles load capacity > 1 ton or GVWR > 12,000 lbs; physical damage only; phys dam on 1989 or older
- Employees/family of Alfa or Trexis Insurance Group; out-of-state licenses in NH NJ NY MA MI
- Prior Trexis cancelled for Underwriting reasons$c$, $c$- Acceptable: foreign & international licenses; SR-22 (AL AZ CO IN KY NV OH TN TX VA; not AR GA MS SC); major violations; DUI; named non-owner (cannot endorse to regular policy)
- Towing & rental reimbursement when Collision purchased
- Mobile app / trexis.com (full online services, 24/7 claims)
- Payment: multiple down/installment options; e-check and credit/debit
- All applications & rejections signed by Named Insured (no exceptions); paperless with email; multiple discounts
- Failure to rate all drivers could result in claim denial; police notified within 24 hrs for hit-and-run/theft/vandalism
- Transfer Discount: proof of prior within 30 days (6+ months continuous PPA) or policy re-rated; salvage/rebuilt acceptable
- Company Plans (AL AZ AR CO IN KY MS NV OH TN TX VA): Trexis (non-scored, traditional non-standard); Trexis One (insurance scoring, comprehensive for new vehicles/full coverage) — Trexis: AL AZ AR CO IN KY NV OH SC TN VA; Trexis One: AR GA IN KY MS OH TN TX VA; Home County State Mutual: TX (equivalent of Trexis)$c$, 270)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;

insert into public.carriers (name, slug, status, product_lines, states, best_for, appetite, requirements, do_not_submit, helpful_hints, sort_order)
values ($c$Geico$c$, $c$geico$c$, $c$not_started$c$, ARRAY[$c$Auto (Standard)$c$,$c$Home$c$,$c$Umbrella/Excess$c$]::text[], ARRAY[]::text[], $c$Missing from the SSPL grid — add your Geico appointment details, login, and product notes here. Paste a Geico appetite guide into the bulletin tool to fill these fields.$c$, null, null, null, $c$Geico was not on the Smart Start carrier grid. Add your appointment status, login URL/username/password, and the product lines you're appointed for. Use the "Update from a bulletin" tool to paste Geico's guidelines and Claude will fill in appetite/requirements/do-not-submit/helpful-hints.$c$, 280)
on conflict (slug) do update set
  name = excluded.name,
  product_lines = excluded.product_lines,
  states = excluded.states,
  best_for = excluded.best_for,
  appetite = excluded.appetite,
  requirements = excluded.requirements,
  do_not_submit = excluded.do_not_submit,
  helpful_hints = excluded.helpful_hints,
  sort_order = excluded.sort_order;
